# Generated by Django 3.2.6 on 2021-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
