# Generated by Django 3.2.6 on 2021-08-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210826_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='translation',
        ),
        migrations.AddField(
            model_name='sentence',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('translation', models.CharField(max_length=200)),
                ('audio', models.CharField(max_length=200)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.file')),
            ],
        ),
    ]
