# Generated by Django 3.2.6 on 2021-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210826_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='sentence',
            field=models.CharField(max_length=200),
        ),
    ]
