# Generated by Django 3.2.6 on 2021-08-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_sentence_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.CharField(max_length=400),
        ),
    ]
