# Generated by Django 3.2.6 on 2021-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_sentence_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
