# Generated by Django 3.2.6 on 2021-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_sentence_exported'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
